"""Tests for etl/extract_chips.py (Task 12) — golden-file chip extraction.

Run from ``etl/``:

    ../.venv/bin/pytest -v            # deterministic, offline

Golden test (brief Step 1): a synthetic 1024x1024 GeoTIFF generated by
``make_fixture_tif.py`` (no binary fixtures in git), chip_size=512 stride=512
-> exactly 4 chips; chip 0 bbox within 1e-6 of the transform-derived corners;
chip_id stable across two runs.
"""
import json
import logging
import uuid
import warnings
from pathlib import Path

import numpy as np
import pytest
import rasterio
from rasterio.errors import NotGeoreferencedWarning
from rasterio.transform import from_origin
from rasterio.windows import Window
from rasterio.windows import transform as window_transform

from make_fixture_tif import BANDS, make_fixture_tif

GOLDEN_TRANSFORM = from_origin(39.0, 22.0, 0.0001, 0.0001)
# literal corners of window (0, 0, 512, 512) under GOLDEN_TRANSFORM
GOLDEN_CHIP0_BBOX = (39.0, 21.9488, 39.0512, 22.0)


def read_jpeg(path):
    """Read a thumbnail, silencing the benign NotGeoreferencedWarning (JPEGs carry no georef)."""
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=NotGeoreferencedWarning)
        with rasterio.open(path) as src:
            return src.read()


def read_window(path, window):
    with rasterio.open(path) as src:
        return src.read(1, window=window)


# --------------------------------------------------------------------------
# Brief Step 1 — golden test (verbatim intent)
# --------------------------------------------------------------------------


def test_golden_four_chips_bbox_and_stable_ids(tmp_path):
    import extract_chips

    scene = make_fixture_tif(
        tmp_path / "S2A_FIXTURE_20261004_0_L2A", transform=GOLDEN_TRANSFORM
    )
    out = tmp_path / "thumbs"
    chips = extract_chips.extract_chips(
        scene_dir=scene, out_dir=out, chip_size=512, stride=512
    )

    # 1024 / 512 at stride 512 -> exactly 4 chips (2x2 grid)
    assert len(chips) == 4

    # chip 0 bbox within 1e-6 of the transform-derived corners
    wt = window_transform(Window(0, 0, 512, 512), GOLDEN_TRANSFORM)
    corners = [wt @ (0, 0), wt @ (512, 0), wt @ (512, 512), wt @ (0, 512)]
    xs, ys = zip(*corners)
    expected = (min(xs), min(ys), max(xs), max(ys))
    assert all(abs(a - b) <= 1e-6 for a, b in zip(chips[0]["bbox"], expected))
    assert chips[0]["bbox"] == pytest.approx(GOLDEN_CHIP0_BBOX, abs=1e-6)
    # row-stride math: index 2 is (row=512, col=0) — one full chip further south
    assert chips[2]["bbox"] == pytest.approx(
        (39.0, 21.8976, 39.0512, 21.9488), abs=1e-6
    )

    # three artifacts per chip: true-color jpg, false-color jpg, 4-band npy
    # in the sibling cache dir (npy lives beside thumbs/, not inside it)
    cid = chips[0]["chip_id"]
    assert (out / f"{cid}.jpg").is_file()
    assert (out / f"{cid}_fc.jpg").is_file()
    npy = np.load(tmp_path / "chips" / f"{cid}.npy")
    assert npy.shape == (4, 512, 512)
    assert npy.dtype == np.float32
    window = Window(0, 0, 512, 512)
    stack = [read_window(scene / f"{band}.tif", window) for band in BANDS]
    assert np.array_equal(npy, np.stack(stack).astype(np.float32))  # B02,B03,B04,B08

    # chip_id = uuid5(scene_id + row + col), deterministic across runs
    assert cid == str(uuid.uuid5(extract_chips.CHIP_NAMESPACE, f"{scene.name}:0:0"))

    # chips_manifest.jsonl — the artifact Task 13 consumes
    lines = [
        json.loads(line)
        for line in (out / "chips_manifest.jsonl").read_text().splitlines()
    ]
    assert len(lines) == 4
    assert lines[0]["chip_id"] == cid
    assert lines[0]["scene_datetime"] == "2026-10-04T08:04:23.747000Z"  # scene.json
    assert Path(lines[0]["chip_path"]).name == f"{cid}.jpg"  # Task 13 thumb basename
    assert Path(lines[0]["chip_path"]).is_absolute()
    assert Path(lines[0]["npy_path"]).is_file()
    assert lines[0]["bbox"] == pytest.approx(list(GOLDEN_CHIP0_BBOX), abs=1e-6)

    # served dir is clean: jpgs + fc jpgs + manifest only (no .aux.xml sidecars)
    expected_files = {f"{c['chip_id']}{s}" for c in chips for s in (".jpg", "_fc.jpg")}
    expected_files.add("chips_manifest.jsonl")
    assert {p.name for p in out.iterdir()} == expected_files

    # chip_id stable across a second run; manifest append dedupes by chip_id
    again = extract_chips.extract_chips(
        scene_dir=scene, out_dir=out, chip_size=512, stride=512
    )
    assert [c["chip_id"] for c in again] == [c["chip_id"] for c in chips]
    assert len((out / "chips_manifest.jsonl").read_text().splitlines()) == 4


# --------------------------------------------------------------------------
# Artifact semantics: previews + .npy band contract (Option B)
# --------------------------------------------------------------------------


def test_jpeg_artifacts_true_and_false_color(tmp_path):
    import extract_chips

    scene = make_fixture_tif(tmp_path / "S2A_JPEG")
    out = tmp_path / "thumbs"
    chips = extract_chips.extract_chips(
        scene_dir=scene, out_dir=out, chip_size=512, stride=512
    )
    cid = chips[0]["chip_id"]
    window = Window(0, 0, 512, 512)
    b04 = read_window(scene / "B04.tif", window)
    b08 = read_window(scene / "B08.tif", window)

    tc = read_jpeg(out / f"{cid}.jpg")
    fc = read_jpeg(out / f"{cid}_fc.jpg")
    assert tc.shape == (3, 512, 512)
    assert fc.shape == (3, 512, 512)
    assert (out / f"{cid}.jpg").read_bytes()[:2] == b"\xff\xd8"  # JPEG magic
    # true-color R channel comes from B04; false-color R channel from NIR B08
    # (JPEG is lossy -> mean-absolute-error tolerance)
    assert np.abs(tc[0].astype(np.int16) - extract_chips.to_uint8(b04).astype(np.int16)).mean() < 8
    assert np.abs(fc[0].astype(np.int16) - extract_chips.to_uint8(b08).astype(np.int16)).mean() < 8
    assert not np.array_equal(tc, fc)  # Option B: true/false previews differ


def test_true_false_color_band_order_and_uint8_stretch():
    import extract_chips

    # one *distinct gradient shape* per band: the per-channel percentile
    # stretch is shift/scale invariant (a*x+b -> same output), so only
    # content shape makes a swapped channel fail these pins
    row = np.repeat(np.arange(64, dtype=np.float32)[:, None], 64, axis=1)
    col = np.repeat(np.arange(64, dtype=np.float32)[None, :], 64, axis=0)
    b02 = col.astype(np.uint16)                    # horizontal
    b03 = row.astype(np.uint16)                    # vertical
    b04 = (col + row).astype(np.uint16)            # diagonal
    b08 = np.abs(col - row).astype(np.uint16)      # V

    tc = extract_chips.true_color(b04, b03, b02)  # B04/B03/B02 -> R/G/B
    assert tc.shape == (3, 64, 64) and tc.dtype == np.uint8
    # each channel is exactly its band's stretch — band order pinned
    assert np.array_equal(tc[0], extract_chips.to_uint8(b04))
    assert np.array_equal(tc[1], extract_chips.to_uint8(b03))
    assert np.array_equal(tc[2], extract_chips.to_uint8(b02))
    assert not np.array_equal(tc[0], extract_chips.to_uint8(b02))  # R is not B02

    fc = extract_chips.false_color(b08, b04, b03)  # NIR-R-G
    assert np.array_equal(fc[0], extract_chips.to_uint8(b08))
    assert np.array_equal(fc[1], extract_chips.to_uint8(b04))
    assert np.array_equal(fc[2], extract_chips.to_uint8(b03))
    assert not np.array_equal(fc[0], extract_chips.to_uint8(b04))  # NIR is not red

    # constant (nodata) chip: no divide-by-zero, deterministic output
    flat = extract_chips.to_uint8(np.full((8, 8), 1234, np.uint16))
    assert flat.dtype == np.uint8 and flat.min() == flat.max()
    assert extract_chips.to_uint8(np.zeros((8, 8), np.uint16)).max() == 0


# --------------------------------------------------------------------------
# Spec §7 — missing data skips scenes with a WARNING, never crashes
# --------------------------------------------------------------------------


def test_missing_band_skips_scene_with_warning(tmp_path, monkeypatch, caplog):
    import extract_chips

    scene = make_fixture_tif(tmp_path / "S2A_NO_NIR", bands=("B02", "B03", "B04"))
    out = tmp_path / "thumbs"
    with caplog.at_level(logging.WARNING):
        chips = extract_chips.extract_chips(
            scene_dir=scene, out_dir=out, chip_size=512, stride=512
        )
    assert chips == []
    assert any("S2A_NO_NIR" in m and "B08" in m for m in caplog.messages)
    assert not out.exists()  # nothing written for a skipped scene

    # same contract on the URL path (band absent from the assets dict)
    def _boom(path):
        raise AssertionError("missing-band scene must never open a dataset")

    monkeypatch.setattr(extract_chips, "open_band", _boom)
    urls = {
        b: f"https://sentinel-cogs.s3.us-west-2.amazonaws.com/x/S2A_NO_NIR/{b}.tif"
        for b in ("B02", "B03", "B04")
    }
    with caplog.at_level(logging.WARNING):
        chips = extract_chips.extract_chips(
            scene_urls=urls, out_dir=out, chip_size=512, stride=512
        )
    assert chips == []
    assert any("B08" in m for m in caplog.messages)


def test_scene_without_crs_skips_with_warning(tmp_path, caplog):
    """SRID 4326 is a hard contract: a CRS-less scene cannot produce a bbox."""
    import extract_chips

    scene = make_fixture_tif(tmp_path / "S2A_NOCRS", crs=None)
    with caplog.at_level(logging.WARNING):
        chips = extract_chips.extract_chips(
            scene_dir=scene, out_dir=tmp_path / "thumbs", chip_size=512, stride=512
        )
    assert chips == []
    assert any("S2A_NOCRS" in m and "CRS" in m for m in caplog.messages)


def test_scene_smaller_than_chip_size_and_default_stride_grid(tmp_path, caplog):
    import extract_chips

    scene = make_fixture_tif(tmp_path / "S2A_GRID")
    # defaults: chip_size=512, stride=128 -> starts 0,128,256,384,512 per axis
    chips = extract_chips.extract_chips(scene_dir=scene, out_dir=tmp_path / "t1")
    assert len(chips) == 25

    tiny = make_fixture_tif(tmp_path / "S2A_TINY", size=400)
    with caplog.at_level(logging.WARNING):
        none = extract_chips.extract_chips(
            scene_dir=tiny, out_dir=tmp_path / "t2", chip_size=512, stride=512
        )
    assert none == []
    assert any("S2A_TINY" in m and "400" in m for m in caplog.messages)


# --------------------------------------------------------------------------
# Primary read path: windowed /vsicurl/ reads over the https COGs
# --------------------------------------------------------------------------


def test_scene_urls_primary_path_windowed_vsicurl_reads(tmp_path, monkeypatch):
    import extract_chips

    # local stand-in data; the seam open_band is patched to serve it
    fixture = make_fixture_tif(tmp_path / "fixture_src")
    scene_id = "S2A_37QDD_20261004_0_L2A"
    root = (
        "https://sentinel-cogs.s3.us-west-2.amazonaws.com/"
        f"sentinel-s2-l2a-cogs/37/Q/DD/2026/10/{scene_id}"
    )
    urls = {b: f"{root}/{b}.tif" for b in BANDS}

    opened = []
    real_open = extract_chips.open_band

    def fake_open(path):
        opened.append(path)
        band = Path(path[len("/vsicurl/") :]).stem
        return real_open(fixture / f"{band}.tif")

    monkeypatch.setattr(extract_chips, "open_band", fake_open)
    chips = extract_chips.extract_chips(
        scene_urls=urls, out_dir=tmp_path / "thumbs", chip_size=512, stride=512
    )
    assert len(chips) == 4
    assert len(opened) == 4  # one open per band, windowed reads inside
    assert all(p.startswith("/vsicurl/https://") for p in opened)

    # scene id derived from the URL's scene directory; ids deterministic
    assert chips[0]["chip_id"] == str(
        uuid.uuid5(extract_chips.CHIP_NAMESPACE, f"{scene_id}:0:0")
    )
    assert chips[3]["chip_id"] == str(
        uuid.uuid5(extract_chips.CHIP_NAMESPACE, f"{scene_id}:512:512")
    )
    # no scene.json over HTTP -> day-precision date from the scene id
    assert chips[0]["scene_datetime"] == "2026-10-04T00:00:00Z"


def test_unsigned_mpc_blob_url_logs_error_and_skips(tmp_path, monkeypatch, caplog):
    """MPC-primary manifests carry UNSIGNED blob hrefs (GET -> HTTP 409).

    The extractor must fail with a clear ERROR pointing at re-signing, not a
    cryptic rasterio failure deep inside /vsicurl/.
    """
    import extract_chips

    scene_id = "S2C_MSIL2A_20261004T074731_R135_T37QDD_20261004T110813"
    root = (
        "https://sentinel2l2a01.blob.core.windows.net/"
        f"sentinel2-l2/37/Q/DD/2026/10/{scene_id}"
    )
    urls = {b: f"{root}/{b}.tif" for b in BANDS}  # no SAS sig= -> 409

    def _boom(path):
        raise AssertionError("unsigned blob href must be gated before rasterio opens it")

    monkeypatch.setattr(extract_chips, "open_band", _boom)
    with caplog.at_level(logging.ERROR):
        chips = extract_chips.extract_chips(
            scene_urls=urls, out_dir=tmp_path / "thumbs", chip_size=512, stride=512
        )
    assert chips == []
    assert any("409" in m and "sign" in m.lower() for m in caplog.messages)

    # control: the same hrefs WITH a SAS signature pass the gate and extract
    fixture = make_fixture_tif(tmp_path / "signed_src")
    signed = {b: urls[b] + "?se=2026-10-07T07:00:00Z&sp=rl&sig=deadbeef" for b in BANDS}
    real_open = rasterio.open

    def fake_open(path):
        band = Path(path[len("/vsicurl/") :].split("?")[0]).stem
        return real_open(fixture / f"{band}.tif")

    monkeypatch.setattr(extract_chips, "open_band", fake_open)
    chips = extract_chips.extract_chips(
        scene_urls=signed, out_dir=tmp_path / "t2", chip_size=512, stride=512
    )
    assert len(chips) == 4


# --------------------------------------------------------------------------
# Georeferencing: bbox SRID 4326 even for UTM scenes (the real S2 case)
# --------------------------------------------------------------------------


def test_utm_scene_bbox_reprojected_to_wgs84(tmp_path):
    from rasterio.warp import transform as warp_transform

    import extract_chips

    utm = from_origin(500000.0, 2400000.0, 10.0, 10.0)  # UTM 37N, 10 m/px
    scene = make_fixture_tif(tmp_path / "S2A_UTM", crs="EPSG:32637", transform=utm)
    chips = extract_chips.extract_chips(
        scene_dir=scene, out_dir=tmp_path / "thumbs", chip_size=512, stride=512
    )
    w, s, e, n = chips[0]["bbox"]
    lons, lats = warp_transform(
        "EPSG:32637",
        "EPSG:4326",
        [500000.0, 505120.0, 505120.0, 500000.0],
        [2400000.0, 2400000.0, 2394880.0, 2394880.0],
    )
    assert w == pytest.approx(min(lons), abs=1e-6)
    assert e == pytest.approx(max(lons), abs=1e-6)
    assert s == pytest.approx(min(lats), abs=1e-6)
    assert n == pytest.approx(max(lats), abs=1e-6)
    assert -180 < w < e < 180 and -90 < s < n < 90  # degrees, never metres


def test_default_out_dir_is_data_thumbs(tmp_path, monkeypatch):
    """out_dir defaults to data/thumbs — the directory Settings.thumbs_dir serves (Task 9)."""
    import extract_chips

    assert extract_chips.DEFAULT_OUT_DIR == Path("data/thumbs")
    scene = make_fixture_tif(tmp_path / "S2A_DEFAULT")
    monkeypatch.chdir(tmp_path)
    chips = extract_chips.extract_chips(scene_dir=scene, chip_size=512, stride=512)
    assert len(chips) == 4
    cid = chips[0]["chip_id"]
    assert (tmp_path / "data" / "thumbs" / f"{cid}.jpg").is_file()
    assert (tmp_path / "data" / "thumbs" / "chips_manifest.jsonl").is_file()
    assert (tmp_path / "data" / "chips" / f"{cid}.npy").is_file()  # sibling cache


# --------------------------------------------------------------------------
# Review fix round 1 — Ruling R12 guards + review findings 2 and 3
# --------------------------------------------------------------------------


def test_dense_grid_warning_and_max_chips_truncation(tmp_path, caplog):
    """R12: >500 projected chips/scene warns; max_chips stops with a record.

    Default stride=128 on a real 10980² scene would produce 6724 chips/scene
    (~26 GiB of .npy) — the brief's signature defaults stay, so the guards
    are a dense-grid WARNING at projection time plus an optional cap.
    """
    import extract_chips

    scene = make_fixture_tif(tmp_path / "S2A_DENSE")
    out = tmp_path / "thumbs"
    # starts floor((1024-64)/32)+1 = 31 per axis -> 961 projected chips; cap at 3
    with caplog.at_level(logging.WARNING):
        chips = extract_chips.extract_chips(
            scene_dir=scene, out_dir=out, chip_size=64, stride=32, max_chips=3
        )

    assert len(chips) == 3  # stopped after N chips
    # (a) dense-grid warning at extraction start, from dims + chip_size/stride
    assert any(
        "dense grid" in m and "stride=32" in m and "961" in m for m in caplog.messages
    )
    # (b) truncation WARNING naming max_chips
    assert any("max_chips" in m and "truncated" in m for m in caplog.messages)
    # truncation recorded in the manifest output (and the returned records)
    lines = [
        json.loads(line)
        for line in (out / "chips_manifest.jsonl").read_text().splitlines()
    ]
    assert len(lines) == 3
    assert all(line.get("truncated") is True for line in lines)
    assert all(record.get("truncated") is True for record in chips)
    # only the truncated chips' artifacts exist (not the 900-chip grid)
    assert len(list(out.glob("*.jpg"))) == 6  # 3 true-color + 3 false-color
    # deterministic ids = first 3 grid positions (row-major from 0,0)
    assert chips[0]["chip_id"] == str(
        uuid.uuid5(extract_chips.CHIP_NAMESPACE, f"{scene.name}:0:0")
    )
    assert chips[2]["chip_id"] == str(
        uuid.uuid5(extract_chips.CHIP_NAMESPACE, f"{scene.name}:0:64")
    )


def test_url_scene_id_unrecognized_skips_with_warning(tmp_path, monkeypatch, caplog):
    """Review finding 2: href parent dir matching neither known id pattern.

    A deeper/differently-nested signed MPC href would degrade scene_id to a
    shared fragment -> identical chip_ids across scenes -> silent overwrite
    and dedupe-dropped manifest lines. spec §7 style: skip with WARNING.
    """
    import extract_chips

    urls = {
        b: f"https://storage.example.com/some/deeper/path/my-scene-folder/{b}.tif"
        for b in BANDS
    }

    def _boom(path):
        raise AssertionError("unverifiable scene identity must skip before opening")

    monkeypatch.setattr(extract_chips, "open_band", _boom)
    with caplog.at_level(logging.WARNING):
        chips = extract_chips.extract_chips(
            scene_urls=urls, out_dir=tmp_path / "thumbs", chip_size=512, stride=512
        )
    assert chips == []
    assert any(
        "unrecognized" in m and "my-scene-folder" in m for m in caplog.messages
    )
    assert not (tmp_path / "thumbs").exists()  # no artifacts


def test_manifest_non_object_line_ignored_not_fatal(tmp_path, caplog):
    """Review finding 3: valid-JSON non-object line used to raise TypeError,
    hit the broad per-scene catch and discard a scene whose artifacts were
    already written."""
    import extract_chips

    scene = make_fixture_tif(tmp_path / "S2A_BADLINE")
    out = tmp_path / "thumbs"
    out.mkdir()
    manifest = out / "chips_manifest.jsonl"
    manifest.write_text('{"chip_id": "existing-chip"}\n42\n', encoding="utf-8")

    with caplog.at_level(logging.WARNING):
        chips = extract_chips.extract_chips(
            scene_dir=scene, out_dir=out, chip_size=512, stride=512
        )
    assert len(chips) == 4  # scene survived the junk line; artifacts kept
    lines = [json.loads(l) for l in manifest.read_text().splitlines()]
    assert len(lines) == 6  # 2 seeded lines left in place + 4 new records
    assert any("malformed" in m for m in caplog.messages)
